[package]
name = "aztec_voting"
type = "bin"
authors = ["HashCloak"]

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v3.0.0-devnet.5", directory="noir-projects/aztec-nr/aztec" }
semaphore = { path = "../aztec-semaphore"}
binary_merkle_root = { git = "https://github.com/privacy-scaling-explorations/zk-kit.noir", tag = "binary-merkle-root-v0.0.1", directory = "packages/binary-merkle-root" }
merkle_trees = { git = "https://github.com/zk-kit/zk-kit.noir", tag = "merkle-trees-v0.0.1", directory = "packages/merkle-trees/" }
poseidon = { tag = "v0.1.1", git = "https://github.com/noir-lang/poseidon" }
ec = { git = "https://github.com/noir-lang/noir-edwards", tag = "v0.2.5"}